language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: hbGcDb6txAxrFau23UjHFKkMDNGZ+F1H4F6ERe4UQpOGBV9CkBz1AU/N1yXcuPpaHRaZmCvGXfviD1l4c1vlLmIDIO4kF/pjAxHJClXDYfYBXwGNLr4m+8tS6Re0+2MRVRdWm7WrKl4cRNSzbU8VcgUbXG+2ElFaWkT5q/SpeHlYwsqRVlcdCW6fATFxe9LKST6wIn3sBbs9KQ0g6aErrP/7mKJXdE7Zjhpy6IzooWLUDE49W9SDNv2LbeJHWI3c9FSP9yOKX5sEgomMXAlSwchXPVnE66jF7OHb4gmtszV27r2AsuzyItAirTgC1AXo/o9wYgQhIQUyvKrJ8begHNU1lg1RMAdV+V7JUQf9Qm1eiI1T1C0tDkPLe20VsNTK9bL7tY8ELky4ICZkIhVmWHsaOLqZvhQs2GCYt/CDgkEq2lbU9KaX0cJJBlQNNqBeorN8k3nMW0v2yyEKl4DgP4O2yZAH8+5is1MbS3XiWpMgCZAhojORaDRJNodR/Y6u4XV1yjjmljnv3UCS7g6lA+0zbTy1qp7cr0fPe5NFCAMo6/NaVOuzkBb4J8MSx1Xkn6X0Zn4aZePOf/6w8iZBoIguC7aVV9ShEdSkec37oqMv4AUCDVHMZgPixdYEWMSHsGYoCMs7jSK8fpNGCh48U7EQU89NZHFFmzVDm7pfmUw=
  file:
    - "mdast-util-to-hast.js"
    - "mdast-util-to-hast.min.js"
  on:
    tags: true
